### ISSUE TITLE
LFS8.3: make 'make' no error,but 'make check' has 2 errors.

### ISSUE THREAD

**Issue by guoyanzhang0817** [gitahead/gitahead#134]
[lfs@archlinux make-4.2.1]$ make check
Making check in glob
make[1]: Entering directory '/mnt/lfs/sources/make-4.2.1/glob'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/make-4.2.1/glob'
Making check in config
make[1]: Entering directory '/mnt/lfs/sources/make-4.2.1/config'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/make-4.2.1/config'
Making check in po
make[1]: Entering directory '/mnt/lfs/sources/make-4.2.1/po'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/make-4.2.1/po'
Making check in doc
make[1]: Entering directory '/mnt/lfs/sources/make-4.2.1/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/mnt/lfs/sources/make-4.2.1/doc'
make[1]: Entering directory '/mnt/lfs/sources/make-4.2.1'
make  loadavg
make[2]: Entering directory '/mnt/lfs/sources/make-4.2.1'
gcc -DLOCALEDIR=\"/tools/share/locale\" -DLIBDIR=\"/tools/lib\" -DINCLUDEDIR=\"/tools/include\" -DHAVE_CONFIG_H -I.  -DTEST   -g -O2 -MT loadavg-getloadavg.o -MD -MP -MF .deps/loadavg-getloadavg.Tpo -c -o loadavg-getloadavg.o `test -f 'getloadavg.c' || echo './'`getloadavg.c
mv -f .deps/loadavg-getloadavg.Tpo .deps/loadavg-getloadavg.Po
gcc  -g -O2 -Wl,--export-dynamic  -o loadavg loadavg-getloadavg.o  -ldl 
make[2]: Leaving directory '/mnt/lfs/sources/make-4.2.1'
make  check-local
make[2]: Entering directory '/mnt/lfs/sources/make-4.2.1'
cd tests && perl ./run_make_tests.pl -srcdir /mnt/lfs/sources/make-4.2.1 -make ../make 
Can't locate test_driver.pl in @INC (@INC contains: /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at ./run_make_tests.pl line 61.
make[2]: *** [Makefile:1282: check-regression] Error 2
make[2]: Leaving directory '/mnt/lfs/sources/make-4.2.1'
make[1]: *** [Makefile:1089: check-am] Error 2
make[1]: Leaving directory '/mnt/lfs/sources/make-4.2.1'
make: *** [Makefile:798: check-recursive] Error 1

**Comment by hackhaslam** [comment]
These errors look unrelated to GitAhead.
