### ISSUE TITLE
LFS 8.3: tar 'make' no error,but 'make check' has 2 errors.

### ISSUE THREAD

**Issue by guoyanzhang0817** [gitahead/gitahead#135]
Please send `tests/testsuite.log' and all information you think might help:

   To: <bug-tar@gnu.org>
   Subject: [GNU tar 1.30] testsuite: 92 failed

You may investigate any problem if you feel able to do so, in which
case the test suite provides a good starting point.  Its output may
be found below `tests/testsuite.dir'.

make[2]: *** [Makefile:1798: check-local] Error 1
make[2]: Leaving directory '/mnt/lfs/sources/tar-1.30/tests'
make[1]: *** [Makefile:1653: check-am] Error 2
make[1]: Leaving directory '/mnt/lfs/sources/tar-1.30/tests'
make: *** [Makefile:1388: check-recursive] Error 1

**Comment by hackhaslam** [comment]
These errors look unrelated to GitAhead.
