### ISSUE TITLE
[BUILDING] Mismatched Git version

### ISSUE THREAD

**Issue by timschumi** [gitahead/gitahead#136]
The file `dep/git/git/contrib/credential/libsecret/git-credential-libsecret.c` is explicitly checked for by CMake, but v2.9.5 of git is explicitly tagged as a submodule. However, the whole libsecret folder does not exist on this revision, it was introduced with v2.11.0.

**Comment by timschumi** [comment]
Thanks for the fast fix :+1:

**Comment by hackhaslam** [comment]
Sure. I somehow managed to check out the wrong tag during the transition to the new repo.
