### ISSUE TITLE
Does not handle & in LFS filenames

### ISSUE THREAD

**Issue by JoeTenniesESLA** [gitahead/gitahead#142]
I am trying to clone a repository that uses git lfs and has files that contain spaces. It seems like the smudge filter is failing out on files that have spaces in their filename.

The error is:      
Failed to clone into 'd:/git/documentskljsdfjhlikdsfjsda' - Cannot read from STDIN. This command should be run by the Git 'smudge' filter
/usr/bin/bash: Patents: command not found
/usr/bin/bash: Secrecy: command not found

The file name is: Exhibit B - Inventions & Patents & Secrecy Agree_Ballard_Andrew.pdf

GitAhead 2.5.2

**Comment by JoeTenniesESLA** [comment]
https://github.com/JoeTenniesESLA/GitAheadFailure

The above is a minimal test case that reproduces the issue. It is fine w/ standard git protocol w/ an '&' in the filename, but it fails at LFS.

I reproduced on GitAhead 2.5.3 on Windows.

**Comment by hackhaslam** [comment]
Thanks for the details. We should be able to fix this for the next build.
