### ISSUE TITLE
Cannot clone repository with ssh key

### ISSUE THREAD

**Issue by SaurabhHarwande** [gitahead/gitahead#144]
I am right now on a windows system. Trying to clone a repository using SSH keys. It gives following error
`Failed to clone into 'C:/Users/CESSHREK/digitalenergy-professional' - Failed to authenticate SSH session: Unable to send userauth-publickey request`

The same if I try to clone through git cli it works.

The SSH key file resides in C:\Users\<user_name>\.ssh\id_rsa

**Comment by hackhaslam** [comment]
It looks like there might be an issue in libssh2 when there's a blank line at the end of the private key after `-----END RSA PRIVATE KEY-----`. Is that the case for you?

https://github.com/ytti/oxidized/issues/1517
https://github.com/libgit2/pygit2/issues/836

**Comment by SaurabhHarwande** [comment]
Ya there was a line break at the end of the file. Just removed it manually through notepad. It still fails but now it happens faster within 3-4 seconds. Used to take more than 30 seconds prior to this. I will try generating new keys and let you know what happens.

**Comment by SaurabhHarwande** [comment]
Hey thanks!
The new version solves the issue. Able to clone repositories with it.
