### ISSUE TITLE
Checking for uncommitted changes - loop

### ISSUE THREAD

**Issue by berti92** [gitahead/gitahead#150]
Hi everyone,
first things first - thank you very much for your work - I really like your application.

I installed the 2.5.3 on my Ubuntu 18.04.

GitAHead does every few seconds "Checking for uncommitted changes" and the GUI freezes a very short time to get these changes.

Is it possible to do this check manually and deactivate the automatic check?

Thank you very much!

**Comment by hackhaslam** [comment]
GitAhead is supposed to automatically rescan in response to changes to files on disk. Is it possible that something is changing the files in your repository?

There isn't an option to disable the filesystem watcher, but it could be added.

**Comment by berti92** [comment]
You are right, a log file was causing this. Thank you!
