### ISSUE TITLE
Stage area context menu is slow to show

### ISSUE THREAD

**Issue by safield** [gitahead/gitahead#154]
GitAhead v2.5.3
Windows 10 1809

I am using gitahead on a large git repo (29000 tracked files).

When I right click on a file in the staging area file list, the context menu takes exceptionally long to show. In worse case, it takes up for 4 second to show the context menu.

Left clicking on files to change the currently selected file, and its associated diff, does not exhibit any performance issues.

The context menu show time can vary significantly from file to file, but I have not been able to determine any characteristic of the files that can be correlated with the time it takes to show.

**Comment by hackhaslam** [comment]
The slow items are the Navigate to -> Next/Previous Revision ones. The lookups happen when the context menu is shown. The only reason to do the lookups up front is to disable those items when there isn't a next/previous revision.

It should be easy to avoid the performance issue by enabling those items unconditionally. That would be sort of unfortunate though. I suppose that it would also be possible to delay the lookup until the submenu is shown. I think I'll look at doing that for now.

**Comment by safield** [comment]
Thanks for the quick reply!!! :) 👍 

Just my two cents.

How would you display to the user the loading state when showing the sub-menu? That could be confusing and result in subsequent bug reports about the sub-menu performance.

I think unconditionally enabling them is a desirable choice. If there is no previous or next item, you simply display a bare bones dialog "No previous revision history exists".

In addition, when dealing with the current working directory, you can assume there is no 'next revision'. Correct? That knowledge could be leveraged to reduce the work done on these check for the working directory commit window.

**Comment by hackhaslam** [comment]
> I think unconditionally enabling them is a desirable choice. If there is no previous or next item, you simply display a bare bones dialog "No previous revision history exists".

I'm sort of averse to that option, but it's probably the right thing to do. You've convinced me.

> In addition, when dealing with the current working directory, you can assume there is no 'next revision'. Correct? That knowledge could be leveraged to reduce the work done on these check for the working directory commit window.

Sure, but that case is already trivial.
