### ISSUE TITLE
Cannot clone from Gitea server behind reverse proxy via https

### ISSUE THREAD

**Issue by IntelligentesTierMaulApollo13** [gitahead/gitahead#175]
GitAhead version: 2.5.4 (prebuilt), 2.5.3 (prebuilt)
OS: Ubuntu 18.04

I like the design of GitAhead so I decided to try it, but I am unable to clone a repository via https. The error which is displayed is the following:
`Failed to clone into '/code/clone' - remote requested authentication but did not negotiate mechanisms`
Apparently the error only occurs with our Git server (based on Gitea behind an Apache2 reverse proxy) and not with GitHub for example, but I've got no problem at all to execute a "git clone <our_repo_url>" to clone from our Gitea server.

Does anybody have an idea what could be wrong?

EDIT: As soon as I remove the binaries called git-credential-gnome-keyring and git-credential-libsecret I am asked for my username and password (I get the error "Unknown SSL error" then; and to be honest I also don't know the reason for that, because I am using Let's Encrypt certificates for the HTTPS traffic)

**Comment by christoph1703** [comment]
Same problem here, similar circumstances (Linux Mint 18.3, GitAhead 2.5.5, Gitea behind Caddy proxy).
I noticed that if I already have a repo locally, GitAhead seems to be able to get some information. It shows a badge over the pull button when there's a new commit on the remote. When I push the button, I get the error again.

I found that disabling `Store credentials in secure storage` under the general options fixes the problem, but then it prompts for credentials at every start. Still, that workaround makes it at least usable.

I really like this project and I hope the problem can be fixed.

**Comment by kas-luthor** [comment]
The problem is that GitAhead doesn't correctly understand when credential helpers report that they haven't found the requested credentials - in this case most likely GNOME keyring.
Until the fix is properly rolled out, just manually add them to the keyring.
