### ISSUE TITLE
files in .gitignore seems to trigger notificationReceived where it should'nt

### ISSUE THREAD

**Issue by seb3s** [gitahead/gitahead#181]
Hi,
to my comprehension files listed in .gitignore should not trigger the refresh of the display (I think via notificationReceived).
In my repo, only directories are correctly handled, but not files. When I update any of the files listed there (and specially log files, which are constantly accessed), the full display is refreshed and because of that I'm losing my navigation.

**Comment by seb3s** [comment]
I'm a bit lost now.
This seems to function properly with files in my gitahead clone repository but not in another private repository.
However in this last repo "git check-ignore --no-index filename" properly indicates that my files are correctly marked as ignored. I really don't understand what's going on. Any idea ?

**Comment by hackhaslam** [comment]
What platform are you on? Each platform uses a different mechanism for watching for changed files.

**Comment by seb3s** [comment]
Yes, sorry Debian 9.
I did further investigations and here is what I've got.
Files are not taken into account when : 
- located in a .gitignore file that is not at the root of the repository
- located in the root level .gitignore file but using a directory in front of the file pattern
So now it seems to me that only files at the root level and with no directory at all in their path are taken into account.

**Comment by hackhaslam** [comment]
Thanks for the details. I expect to release a new build with the fix within the next couple of days.

**Comment by seb3s** [comment]
Hello,
I was able to recompile the project with your fix and that has corrected it. Thanks !
I had to add a -no-pie option in CMakeCache.txt (gcc 6 under debian stretch) in order to generate a executable that's runnable from the filemanager.
I put it there :
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-no-pie
I document it there as it can be useful for others.
How to you build your releases ? Do you have a process to get the set of files in a clean way ?
Cheers,
Sébastien.

**Comment by hackhaslam** [comment]
I build on CentOS 6 for compatibility reasons. I'm not familiar with the issue you're describing when building without the -no-pie flag.

> Do you have a process to get the set of files in a clean way ?

What do you mean? The process for building an absolutely clean build is to blow away the build directory and create a new one. I *don't* do that for the official release.

**Comment by seb3s** [comment]
I mean for the official release.
I've got my so files in the Qt install directory. How do I get everything properly packed so that I can move it elsewhere ?

**Comment by hackhaslam** [comment]
Release packages are created using cpack. Run `make package` (or `ninja package` depending on which generator you used). On Linux that creates the self-extracting shell script installer. If you just want to relocatable install directory you can build the `install` target, but take care to set the `CMAKE_INSTALL_PREFIX` to something other than /usr/local first, since GitAhead doesn't install in the typical bin/lib/share/etc. directory structure.

**Comment by seb3s** [comment]
Yeah, ninja package does it. That's cool.
Thanks again. I'm totally new to C++ but I'm up and running to try things as of now.
Cheers
