### ISSUE TITLE
Doesn't recognise new submodule when switching to branch with new submodule

### ISSUE THREAD

**Issue by osbatgill** [gitahead/gitahead#183]
I have a parent project P that contains some submodules.  I'm working on a branch of this parent bP.  I add a new submodule to the project, commit and push my branch.  Ok so far.
Next, using GitAhead I check out the parent P to a fresh location.  In GitAhead I switch to bP using "new local branch" in the Remotes tab.  I go to the Submodule -> Update... menu, and my new submodule does not appear.  Using the refresh and fetch buttons doesn't make any difference.
If I restart GitAhead, the Submodule -> Update... menu now shows the new submodule.

**Comment by hackhaslam** [comment]
GitAhead caches the list of submodule names for performance reasons. I made a small change to invalidate the cache when the HEAD changes and when clicking on refresh.

**Comment by osbatgill** [comment]
Nice job - cheers!
