### ISSUE TITLE
[Question] dependencies and submodules

### ISSUE THREAD

**Issue by noraj** [gitahead/gitahead#184]
It is maybe an extremely noob question. Why is is required to include all dependencies as git sub-module ? (like libssh2 or openssl). Can't we build gitahead without them and then ask for libraries on user system?

Imagine if every application that need openssl as dependency includes it in its source ...

**Comment by hackhaslam** [comment]
There are a number of reasons for including dependencies as submodules and bundling them with the application. They're not available as system libraries on all platforms. In some cases we require specific versions of libraries for all features to work. For example, OpenSSL isn't available as system library on macOS and Windows and version 1.1.1 is required to support Ed25519 SSH keys (see #140).
