### ISSUE TITLE
Can you also release gitahead as zip-file ?

### ISSUE THREAD

**Issue by ststeiger** [gitahead/gitahead#189]
I have no admin rights on the corporate PC. 
The .exe only works with admin-rights. 
Could you release it as .zip, so I can just unzip it ?

**Comment by 0x326** [comment]
Is it possible to unzip the `.exe` with 7zip?  That's what [Scoop](https://github.com/lukesampson/scoop) usually does

**Comment by ststeiger** [comment]
@0x326: No it isn't, already tried.

**Comment by RoyiAvital** [comment]
It will be great to a have a package which also includes GIT in it and doesn't require it to be pre installed.

Something like SmartGit is doing with their packages.

**Comment by hackhaslam** [comment]
@RoyiAvital GitAhead does *not* require git to be preinstalled. It is fully standalone.

**Comment by RoyiAvital** [comment]
Does it write anything to the regitsry?
Does it use Environment Variables (Writing to `%APPDATA%` or `%UDERPROFILE%`?

**Comment by hackhaslam** [comment]
@RoyiAvital Yes absolutely. It saves settings.

**Comment by RoyiAvital** [comment]
Does it save to registry,t using Environment Variables or both?

**Comment by hackhaslam** [comment]
@RoyiAvital GitAhead writes to both the registry and the APPDATA directory on Windows. What are you getting at? If you have a concern, please open a new issue for it.

**Comment by RoyiAvital** [comment]
I wanted to have a Portable version of it.
Version which all configuration data is written to the local folder of GitAhead and not spread around the system folders.

So if it was limited to Environment Variables I could build a `.bat` launcher which adjust the values of those variables to the local folder.

Yet, I don't have a way to prevent it using the registry.

**Comment by hackhaslam** [comment]
GitAhead uses `QSettings` (with the default registry format) for most global settings. There's also a git-compatible global config file that uses `QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation)` to get the APPDATA path. I don't believe that the actual environment variable is queried in either case. It uses some internal Windows API. It still ought to be possible to influence the location of the APPDATA settings in some way, but I don't know how.
