### ISSUE TITLE
Add button to open repository folder

### ISSUE THREAD

**Issue by hvariant** [gitahead/gitahead#193]
On Windows, this would open the folder in Explorer. On Linux, probably whatever file manager is available.

**Comment by gamesover** [comment]
shouldn't it be an existing function? I opened the app, there is a button called `Open exisiting repository`

**Comment by hvariant** [comment]
I can't seem to find the button, can you show me a screenshot? @gamesover

**Comment by hackhaslam** [comment]
There isn't an option to open the current repository folder in Explorer/Finder/etc. The `Open existing repository` button is unrelated to this request.

**Comment by gamesover** [comment]
ah, I misunderstand it. Sorry, @hackhaslam @hvariant

**Comment by jpwhiting** [comment]
There is an existing tool to open any file if you right click on it in GitAhead. On mac it's "Show in Finder", on windows it's "Show in Explorer" Does that meet your needs @hvariant ?

**Comment by hvariant** [comment]
@jpwhiting Didn't know about this feature, that definitely solves my problem. Thanks!
