### ISSUE TITLE
Push to failing silently

### ISSUE THREAD

**Issue by jpwhiting** [gitahead/gitahead#197]
I cloned gitahead from the main repository. Then added a fork as jpwhiting remote. After origin/master was changed by a merge I pulled my local master branch (which has origin/master as upstream) to update it to what's in origin/master. Then in GitAhead I chose Push to... Selected "jpwhiting" remote and master branch and hit "Push" button. The log that popped up showed everything is up to date, yet "jpwhiting/master" is still 2 commits behind as shown in both gitk and gitahead.

**Comment by hackhaslam** [comment]
Thanks! I just checked in a fix in 4c64b78. It was bailing out when the branch you were pushing was already up-to-date with its upstream.

**Comment by jpwhiting** [comment]
Awesome, thank you.
