### ISSUE TITLE
Amend commit try to reset

### ISSUE THREAD

**Issue by hrotkogabor** [gitahead/gitahead#206]
Clicking "Repository/Amend Commit" will pop up a Reset window, and asks is I want to reset my branch to a commit. Of cource I am not.

**Comment by hackhaslam** [comment]
Amending the latest commit is implemented as reset and it needs the same warning about rewriting history. The git commit documentation says:

       --amend
           Replace the tip of the current branch by creating a new commit. The
           recorded tree is prepared as usual (including the effect of the -i
           and -o options and explicit pathspec), and the message from the
           original commit is used as the starting point, instead of an empty
           message, when no other message is specified from the command line
           via options such as -m, -F, -c, etc. The new commit has the same
           parents and author as the current one (the --reset-author option
           can countermand this).

           It is a rough equivalent for:

                       $ git reset --soft HEAD^
                       $ ... do something else to come up with the right tree ...
                       $ git commit -c ORIG_HEAD

           but can be used to amend a merge commit.

           You should understand the implications of rewriting history if you
           amend a commit that has already been published. (See the
           "RECOVERING FROM UPSTREAM REBASE" section in git-rebase(1).)

**Comment by hrotkogabor** [comment]
Thanx for the clarification! Maybe the window title could be confirmatory like "Reset with amend".
