### ISSUE TITLE
Add support for "Include ~/.ssh/my_config" syntax

### ISSUE THREAD

**Issue by wxiaoguang** [gitahead/gitahead#217]
I have a lot of ssh configs so I have to split the `.ssh/config` into small files:

eg:
```
$ cat ~/.ssh/config

Include ~/my_servers/*
Include ~/compan_servers/*
...
```

It seems that GitAhead can not find the correct key in the included config files and reports `     Unable to push to 'origin' - failed to find SSH identity file`

**Comment by hackhaslam** [comment]
No, it isn't currently supported. Unfortunately, libssh2 doesn't support parsing OpenSSH config files, and libgit2 only support libssh2. GitAhead implements its own simplistic parsing of config files. This could probably be added without too much difficulty.
