### ISSUE TITLE
Input of accented characters not working

### ISSUE THREAD

**Issue by Dominiquini** [gitahead/gitahead#223]
I am unable to type any accented letter in any of the input texts of the application, like the field of the commit message. But I'm able to copy-paste some accented letter created elsewhere.

**SO:** Ubuntu 18.04
**APP_VERSION:** 2.5.7
**LANGUAGE_INTERFACE:** en_US
**LANGUAGE_KEYBOARD:** pt_BR

**Comment by hackhaslam** [comment]
Are you using the compose key to input accented characters? It looks like GitAhead is missing Qt's compose plugin. I just made a change to bundle that plugin in 9f1822db91095cd7ff4b4d755551392c8574a135. That will be included in the next build

**Comment by hrotkogabor** [comment]
I can enter Hungarian letters, like űáúőóüöí without any problem.
lang code: hu_HU

**Comment by Dominiquini** [comment]
I don't use the compose key. Only the accent characters of my keyboard followed by the letter I want to modify. ('~' + 'a' = 'ã')
In the app, none accent keys are printed, even when pressed multiple times in a row. The only accented letter that I capable of input is 'ç', because my keyboard have a key for that character.
I using a keyboard with layout "ABNT2".

Thank you.

**Comment by hackhaslam** [comment]
I just released a new build with the compose input method change. I believe this will fix the problem. @Dominiquini can you test it please?

**Comment by Dominiquini** [comment]
I updated the app and tested it today and it's working.
I'll close the issue!

Thanks
