### ISSUE TITLE
Shortcut for staging files?

### ISSUE THREAD

**Issue by robitalec** [gitahead/gitahead#227]
Currently, with GitAhead I can write a commit message, then commit and push solely with the keyboard. If I'm committing often, after editing a single file, it would be really useful to hit e.g. CTRL+SHIFT+S to stage that file, then commit (CTRL+SHIFT+C) and potentially push (CTRL+SHIFT+P) all in one go.

Not a big deal to move over to the mouse, but if there was a shortcut for staging that would be sweet. 

Am I missing the shortcut for staging files? If not, is this something others would also use?

Thanks!

**Comment by hackhaslam** [comment]
@kas-luthor added shortcuts to stage/unstage all files. That's now available in the current release. Using the keyboard to stage individual files would require some more thought.

**Comment by robitalec** [comment]
Yes, I'm not sure individual files would be as useful/straightforward. 
Thanks @kas-luthor and @hackhaslam, really impressed with how quick this was added.
