### ISSUE TITLE
Bitbucket: Checking for uncommitted changes Loop

### ISSUE THREAD

**Issue by dgalli1** [gitahead/gitahead#236]
If i open a private repository with a https:// origin which is hosted on Bitbucket it will check for new commits forever.
If i open the same repository over ssh with a already configured ssh key it seems to work fine.

I tried to reproduce the same issue with github. But this problem only seems to apply to Bitbucket

Edit: Forgot to mention it but im running on Linux  on the latest master branche

**Comment by dgalli1** [comment]
Funny enough this issue doesn't appear anymore when im using my changes from this PR: https://github.com/gitahead/gitahead/pull/237

Also the issue doesn't seems to be tied with the ssh/https origin. The issue has to somewhere else

**Comment by dgalli1** [comment]
Okay my first guess was completely wrong i found out what the issue really is.
If i started the application from VSCode everything seems to be fine so i checked the enviroment Variables for any difference.

This issue only appears when the LANG variable is set to this:
LANG=de_CH.UTF-8
If i now change it something else like:
LANG=de_DE.UTF-8

It seems to work fine. 
It seems like this variable never gets accessed with qgetenv, so this issue probably has something to do with libgit?

**Comment by hackhaslam** [comment]
I don't think libgit2 does anything with that environment variable, at least not directly. I expect Qt to use it to initialize its locale, but I don't know how that could affect GitAhead's status diff.

If you're still able to recreate this, then I'd suggest setting a break point to at test whether it's stuck in the same status diff operation or if it's restarting it continuously.

**Comment by dgalli1** [comment]
Finally i got the time to look into somemore...
Just to realise  that its fixed now. I definitly should have pulled your latest version before trying to find the bug :man_facepalming:. Whatever the reason might be its fixed and this issue can be closed
