### ISSUE TITLE
Can't open new Repos from first Remote Account

### ISSUE THREAD

**Issue by dgalli1** [gitahead/gitahead#238]
The remote section in the sidebar won't work properly if a repository is not yet cloned.
The CloneDialog should appear on double press but nothing happens. Because the logic which checks if a repo is already open (https://github.com/gitahead/gitahead/commit/267d0839ff89eb50fe5bea05640c018d5c9e9372). Prevents any further action.

This seems to only apply for the first account in the remote list.

**Comment by hackhaslam** [comment]
Thanks for the report! This is fixed for the next build.
