### ISSUE TITLE
Cannot not stage submodule

### ISSUE THREAD

**Issue by ysalmon** [gitahead/gitahead#243]
I committed in a submodule and the diff view of the "parent" repo reflects this. However, gitahead automatically stages the submodule change and does not let me unstage it, which is annoying because, to create a nice and coherent history in the main repo, I would like to make an unrelated commit before committing the submodule change.

Is this a limitation of gitahead or is there something I am doing wrong ?

**Comment by hackhaslam** [comment]
That's not how it's supposed to work. This looks like another recent regression. I'm still investigating.
