### ISSUE TITLE
encoding selector needed

### ISSUE THREAD

**Issue by maggiedot** [gitahead/gitahead#246]
Opening a local repo of Gitlab, found the comment in Chinese does not shown correctly, but, the commit message which also in Chinese is ok, can we provide a encoding selector to make this better or how can I re-configure this? 

Thanks! 

![image](https://user-images.githubusercontent.com/6770380/62598760-fb6da300-b91c-11e9-9f37-7028cf2fbc0f.png)

**Comment by hackhaslam** [comment]
The diff encoding can be set in Tools -> Options... -> Diff -> Character Encoding. It defaults to the system locale's default encoding. The commit message, on the other hand, is typically UTF-8 encoded, regardless of your system locale.
