### ISSUE TITLE
Crash when click on some of the menu items

### ISSUE THREAD

**Issue by quwisky** [gitahead/gitahead#247]
Application crashes when I try to click the following menu items:
- Repository -> Configure Repository
- Branch -> Configure Branches
- Remote -> Configure Remotes
- Configure Settings button 

With this error message:
`QObject: Cannot create children for a parent that is in a different thread.
(Parent is LogEntry(0x3060100), parent's thread is QThread(0x1d38b70), current thread is QThread(0x2ebc520)
QObject::setParent: Cannot set parent, new parent is in a different thread
Segmentation fault (core dumped)`

**I tried it with two of my repositories and the error only occured with my angular project repo.**

System information:

- OS: Ubuntu 19.04 x86_64 
- Kernel: 5.0.0-23-generic 
- DE: GNOME 3.32.2 
- CPU: Intel i7-8550U (8) @ 4.000GHz 
- GPU: Intel UHD Graphics 620 
- GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 
- Memory: 32065MiB
- Qt version: 5.12.2

**Comment by hackhaslam** [comment]
@quwisky Can you post a stack trace?

**Comment by quwisky** [comment]
Can you help me, how can i get stack trace? Is there a debug option to start the application with?

**Comment by hackhaslam** [comment]
Start it in gdb like this:

    % gdb path/to/GitAhead
    (gdb) run

Then make it crash and run the backtrace command:

    (gdb) bt

**Comment by quwisky** [comment]
Thank you for help!

Here is the trace:
[GitAhead_v2.5.8_stack_trace.txt](https://github.com/gitahead/gitahead/files/3496450/GitAhead_v2.5.8_stack_trace.txt)

**Comment by hackhaslam** [comment]
Thanks for providing the stack trace. That helped to recreate the issue. The crash is fixed for the next build.

It looks like this is happening on a repository which has had LFS initialized on it, but the `git-lfs` executable can't be found.  Unfortunately, GitAhead doesn't bundle git-lfs. It has to be installed separately. You should be able to work around the issue by installing git-lfs.

**Comment by quwisky** [comment]
I see. Thank you for your help.
