### ISSUE TITLE
[2.5.9] libgit2 submodule depends on unexistent commit

### ISSUE THREAD

**Issue by denisfalqueto** [gitahead/gitahead#250]
On tab v2.5.9, it's not possible to run git submodule update, for the following reason:

error: Server does not allow request for unadvertised object 9a119ee15416dda3ae7579c5788fe5faa2d42431
Fetched in submodule path 'dep/libgit2/libgit2', but it did not contain 9a119ee15416dda3ae7579c5788fe5faa2d42431. Direct fetching of that commit failed.

It's working fine on branch master

**Comment by hackhaslam** [comment]
Yeah, I messed that up. Try again. It should be fixed now. I'll have to change my process somewhat going forward.

**Comment by denisfalqueto** [comment]
Yes, it's working fine now. Thank you for being so fast!
