### ISSUE TITLE
Failed to authenticate SSH session

### ISSUE THREAD

**Issue by Flo3561** [gitahead/gitahead#251]
When trying to fetch the following error is shown in the log with version 2.5.9 (was working with 2.5.8). Installed on Manjaro system with AUR.
CLI command "git fetch" is working as expected.

> [-] 11:37 - Fetch - origin
>      Unable to fetch from 'origin' - Failed to authenticate SSH session: Unable to send userauth-publickey request

**Comment by Flo3561** [comment]
Yes. I installed it from AUR package which is now up to date on version 2.5.10 (still not working).
Why should I try to rebuild completely from scratch?

**Comment by hackhaslam** [comment]
I'm not asking you to rebuild from scratch. I'm asking you to try the official download from gitahead.com instead of the AUR package.

**Comment by Flo3561** [comment]
Okay got it. Seems working. I have commented the failure in the AUR package repository. Hope they will correct it soon. 
So I think this issue can be closed.
Thanks for your help @hackhaslam!
