### ISSUE TITLE
failed to find SSH identity file

### ISSUE THREAD

**Issue by lkzcgfvf** [gitahead/gitahead#254]
Hi

I have multiple github accounts. My "C:\Users\user\.ssh\config" configured to use different keys. 
Command line git client works fine (as well as GitHub Desktop), however GitAhead shows this error when I try to clone project.
"Failed to clone into 'c:/tmp/project' - failed to find SSH identity file"

GitAhead 2.5.9.  Windows 7. 
Here is my config:

Host x1.github.com
HostName github.com
PreferredAuthentications publickey
IdentityFile c:\x1\keys\github\id_rsa 
IdentitiesOnly yes

Host x2.github.com
HostName github.com
PreferredAuthentications publickey
IdentityFile c:\x2\keys\github\id_rsa 
IdentitiesOnly yes

These commands successfully clone repos
git clone git@x1.github.com:company1/project.git
git clone git@x2.github.com:company2/project.git

Pls help.

**Comment by hackhaslam** [comment]
It's available now. Let me know if it fixes the issue for you.

**Comment by lkzcgfvf** [comment]
It resolved issue. However I see another problem now.
If I have "puttyagent" running and at least one key is loaded into it then GitAhead doesnt work.
Keys that are loaded in "puttyagent" are NOT used in GitHub.

Error is:
Unable to fetch from 'origin' - error authenticating: Username/PublicKey combination invalid
