### ISSUE TITLE
Feature Request: Compact History View

### ISSUE THREAD

**Issue by Gr3q** [gitahead/gitahead#261]
Love the Software, but the history view can display only 13 commits at best on a Full HD display.

Would be nice to have an (optional? ) compact view for the history panel, 1 line for one commit.

Option could be added here:
![kép](https://user-images.githubusercontent.com/22377521/64189238-c1d07f00-ce6b-11e9-8b5e-9ae51f6e0008.png)

An example, commit info not necessarily in this order:
![example](https://user-images.githubusercontent.com/22377521/64190018-5be4f700-ce6d-11e9-839f-29589f15aae3.jpg)

**Comment by Hugo-Trentesaux** [comment]
We could do something like 

    git log --graph --pretty=format:'%h -%d %s (%cr) %an'

**Comment by Gr3q** [comment]
Looks really good to me (I personally prefer %d first, but I'm good with anything as long as it fits one line)

Long descriptions might need to be truncated based on the available width _(not familiar with Qt so idk whats possible)_, or hide some of the fields when width is constrained?

**Comment by Hugo-Trentesaux** [comment]
Is around there : https://github.com/gitahead/gitahead/blob/a63721aae33ba6cb414f4781904acccecaa259d0/src/ui/CommitList.cpp#L815-L825 maybe I will spend some time on it.

**Comment by Gr3q** [comment]
I did something like this today.

![image](https://user-images.githubusercontent.com/22377521/64279954-029dc600-cf48-11e9-9097-8a7009ab6473.png)

Of course the hard parts are not done:
* **Everything I've done overwrites the existing style!**
* No Date and Name (don't know where to put them)
* Badge max width is hardcoded
* Maybe Star is better on the left, before the graphs
* Star is misaligned
* Add Ellipsis char at the end of description text?

If you want to have a look, or build upon it, its in my [fork](https://github.com/Gr3q/gitahead/tree/compact-history)
