### ISSUE TITLE
rmdir failed on checkout

### ISSUE THREAD

**Issue by char101** [gitahead/gitahead#274]
Hi,

When trying to checkout the master branch from current branch (which is ahead of the master branch, also the master branch have a commit that delete a file in it), I got this error:

`[-] Unable to checkout 'master' - could not rmdir '<app-path>/src/': The process cannot access the file because it is being used by another process.`

Also the file that was being deleted in the master branch is now added as being deleted in the index, although the branch was not successfully checked-out.

I can checkout the master branch cleanly using git command.

It looks like the error come from [RepoView.cpp#L782](https://github.com/gitahead/gitahead/blob/08727c527f57847ecef863f4ea3599495cfd911a/src/ui/RepoView.cpp#L782) which tries to lfs lock the directory (?). But this repository doesn't use LFS.

**Comment by kas-luthor** [comment]
The line you mentioned doesn't display the error message - it will only log "Unable to lock" or "Unable to unlock"

Does the error occur if no other application is running on your system?
If the error is reproducible, are there any processes with an open handle to it (try using `lsof`)?

**Comment by char101** [comment]
I'm using Windows. It is not becaue of locked files, because like I said before, git itself works fine on the repository running the same case (checking out master branch). Also why does `lfsSetLocked` get called even though the repository does not use LFS?

**Comment by char101** [comment]
Oh by the way, I think I should make this clear. Yes the `<app-path>/src` is locked by my file explorer and that is why I was lucky. Otherwise it would have been removed by gitahead.

The problem is not that it is locked but gitahead is trying to remove the source code directory of my application! It is a Vue app and `src` exists on both branches. There is no reason whatsoever to remove it.

**Comment by hackhaslam** [comment]
What makes you think the error was in `lfsSetLocked`? Did you set a breakpoint there? That same error format occurs in various places. It looks to me like that error is coming from libgit2.

**Comment by char101** [comment]
You are right, looking at the source code it seems I must have been mistaken because the verb in that position is either lock or unlock.

**Comment by char101** [comment]
There is similiar issue here https://stackoverflow.com/questions/37073460/git-in-tfs-branch-switching-could-not-rmdir so I guess it isn't caused by gitahead itself but by its underlying library. Thanks.
