### ISSUE TITLE
Feature Request: Privacy Setting in "Options"

### ISSUE THREAD

**Issue by PolyVector** [gitahead/gitahead#281]
After months of using this wonderful program, I JUST discovered the hidden option to opt-out of statistical usage reporting.  Currently this setting is in Help(not where users go for settings)->About(not where users go for settings)->Privacy(fair enough) and then placed within the "Privacy Policy" text!

I humbly request that this setting be placed in Tools->Options->General (or Tools->Options->Update) where most users would expect it to be.

"We respect your right to privacy" are empty words when a basic privacy setting is buried and camouflaged.

**Comment by hackhaslam** [comment]
I will add that option to the settings as well.

**Comment by PolyVector** [comment]
Thank you!  I didn't expect such a quick response. :)

Cheers!

**Comment by hackhaslam** [comment]
This is done in version 2.5.11. The option is in the 'General' settings panel.
