### ISSUE TITLE
Compile on MacOS

### ISSUE THREAD

**Issue by Maickonn** [gitahead/gitahead#282]
Hello, @hackhaslam !

I trying compile on MacOS, but I receiving this error:

> CMake Error at pack/CMakeLists.txt:33 (get_target_property):
>   get_target_property() called with non-existent target
>   "Qt5::QMacStylePlugin".

I am not finding this plugin anywhere and he is not mentioned in the README.MD.

**Comment by hackhaslam** [comment]
What version of Qt are you using? Did you build Qt yourself?

**Comment by Maickonn** [comment]
> What version of Qt are you using? Did you build Qt yourself?

I tried compile on Qt Version 5.9.8 and 5.12.5.

 I used the Maintenance Tool, follow the screenshots:

![Screen Shot 2019-10-03 at 4 53 45 PM](https://user-images.githubusercontent.com/1365683/66159507-8528ac80-e5fe-11e9-9d38-09ab9a8be6d7.png)

![Screen Shot 2019-10-03 at 4 54 01 PM](https://user-images.githubusercontent.com/1365683/66159508-8528ac80-e5fe-11e9-8c7e-4120c0705e50.png)

**Comment by hackhaslam** [comment]
The cmake config file for that plugin is found at ~/Qt/5.12.5/clang_64/lib/cmake/Qt5Widgets/Qt5Widgets_QMacStylePlugin.cmake. That target should be automatically added when the QtWidgets module is imported. Maybe the cmake output offers some clue why it wasn't found?

**Comment by Maickonn** [comment]
> The cmake config file for that plugin is found at ~/Qt/5.12.5/clang_64/lib/cmake/Qt5Widgets/Qt5Widgets_QMacStylePlugin.cmake. That target should be automatically added when the QtWidgets module is imported. Maybe the cmake output offers some clue why it wasn't found?

I fixed the problem by deleting all files on release folder and build again with the Qt 5.12.5. But the executable generated are with 2 KB size and "damaged". lol

![Screen Shot 2019-10-03 at 5 35 29 PM](https://user-images.githubusercontent.com/1365683/66162206-4695f080-e604-11e9-8ced-e5393739cd6a.png)

**Comment by Maickonn** [comment]
> > The cmake config file for that plugin is found at ~/Qt/5.12.5/clang_64/lib/cmake/Qt5Widgets/Qt5Widgets_QMacStylePlugin.cmake. That target should be automatically added when the QtWidgets module is imported. Maybe the cmake output offers some clue why it wasn't found?
> 
> I fixed the problem by deleting all files on release folder and build again with the Qt 5.12.5. But the executable generated are with 2 KB size and "damaged". lol
> 
> ![Screen Shot 2019-10-03 at 5 35 29 PM](https://user-images.githubusercontent.com/1365683/66162206-4695f080-e604-11e9-8ced-e5393739cd6a.png)


I fixed the problem. I just compiled using Qt Creator to compile instead of ninja, so it worked.
Thanks! :D
