### ISSUE TITLE
Binary segfaults

### ISSUE THREAD

**Issue by w3bb** [gitahead/gitahead#286]
I've tried to install GitAhead by using the self extracting archive. I've tried versions 2.5.10 and 2.5.9 and each extracted binary simply Segfaults.

I'm on Gentoo x86_64 using OpenRC.

**Comment by hackhaslam** [comment]
Can you please upload a stack trace? Run GitAhead in gdb like this:

    bash> gdb path/to/GitAhead
    gdb> r
    ... wait for crash ...
    gdb> bt

**Comment by w3bb** [comment]
So I found out what was wrong. I switched from Xinerama to Xrandr to solve another issue I was having. After switching it works perfectly.
