### ISSUE TITLE
Displaying profile picture (avatar) for non-primary GitHub email addresses

### ISSUE THREAD

**Issue by beowulfenator** [gitahead/gitahead#290]
Hi!

For some reason, commits that I have made using my primary email address from my GitHub account have the correct profile picture, but commits made using the other (secondary) email address do not have an avatar.

Is this intentional?

**Comment by hackhaslam** [comment]
GitAhead merely requests your profile picture from gravatar.com with the commit author's email address.

**Comment by beowulfenator** [comment]
I never realized that, thank you!
