### ISSUE TITLE
Mention the license in the "About" window

### ISSUE THREAD

**Issue by raphj** [gitahead/gitahead#292]
Hello,

Thank you for this tool. It is very useful.
In the about window, we can read "Copyright © 2016-2018 Scientific Toolworks, Inc. All rights reserved". Which is a bit confusing since GitAhead is under the MIT license.

 This bug report is a suggestion to mention the license, the website and the github repository in this window.

**Comment by hackhaslam** [comment]
It's appropriate to mention copyright in an open source project. I've clarified the text in version 2.5.11 to indicate that there are other contributors. I also don't feel like it's necessary to mention the license in the about dialog. It's in the source code.

**Comment by raphj** [comment]
Just to be clear, it was the mention "All rights reserved" that I found confusing. Of course, the copyright mention is absolutely appropriate.
