### ISSUE TITLE
Include fetch all

### ISSUE THREAD

**Issue by christiankral** [gitahead/gitahead#293]
I noticed that Gitahead seems not to support:

```bash
# See https://git-scm.com/docs/git-fetch
git fetch --all
```
Instead one has to fetch each remote repository manually which is a lot of time effort. Alternatively one could certainly use the terminal to fetch all remotes, but having this included in the `Remote` menu and as an additional clickable button

![image](https://user-images.githubusercontent.com/4184218/66482626-a9273a80-eaa3-11e9-8463-8d4c941517d0.png)

would help a lot to maintain a smooth work flow.

**Comment by christiankral** [comment]
The feature of `git fetch -all` is particularly important when many contributors contribute through pull requests in a forked repository. I think it were quite straight forward (for a software developer who I am not) to implement this feature, as "just" a git command has to be processed. The `fetch --all` shall then also go into the Remote menu.

![image](https://user-images.githubusercontent.com/4184218/67809851-ca26ee00-fa99-11e9-9ca7-730d6a062349.png)

**Comment by hackhaslam** [comment]
This is added to the 'Remote' menu in version 2.5.11.

**Comment by christiankral** [comment]
Thanks a lot.
