### ISSUE TITLE
Diff isn't working ok

### ISSUE THREAD

**Issue by lelduayen** [gitahead/gitahead#294]
When I select files the diff works ok for some files but isn't working for others. 
The problem is that is not detecting the changes and marking the hole file content as changed. If I check with Smartgit the same file I can see the differences ok, I'm going to try with git bash or similar for the next time. 

Environment:

- gitAhead 2.5.10
- Windows 10

What other info can I submit? I think that a screen capture is not going to be helpful because the files are bigger than you can see without scrolling.

**Comment by hackhaslam** [comment]
There's an option to ignore whitespace in the little gear icon in the upper right corner of the diff file list. If you turn on that option, do you see the same diff as the other client?

**Comment by lelduayen** [comment]
Sorry about the late response, I missed the email notification. And about the whitespace option, I didn't try it. Let me check on monday if I can reproduce the problem (because it happens with some files only as I previously said).

**Comment by lelduayen** [comment]
Well, we have some light about this: 

- If we check the ignore whitespace option it works ok.
- We use eclipse, and in there if you check the option File -> Convert line delimiters to -> Unix then the problem is gone.
![image](https://user-images.githubusercontent.com/11880357/67214881-e4f0c700-f3f6-11e9-8836-9e54581c79fb.png)
- The configuration in git (pull windows delimiters, push unix delimiters) doesn't fix the problem



All indicates that the problem are the line delimiters (windows/unix), and that gitahead doesn't like windows' line delimiters.

**Comment by hackhaslam** [comment]
It's not that GitAhead doesn't "like" Windows line endings, it simply sees them as different when they change. Compare the output of GitAhead with command line git. Try `git diff` and `git diff -w`.  You should see the same thing as GitAhead.

Changing the `core.autocrlf` config variable will not make any difference until you start checking out or adding files to the index. Files with existing non-whitespace changes should converted manually with your editor like you've described.

**Comment by lelduayen** [comment]
@hackhaslam thank you very much for your explanation, I'm gonna check the output with command line.
Sorry about the missunderstanding, I'm closing this issue right now. 

Regards!
