### ISSUE TITLE
Feature request: not expand all remotes when basically anything is done

### ISSUE THREAD

**Issue by GuiRitter** [gitahead/gitahead#295]
Hi everyone.

After GitKraken's questionable decision to hide private repos behind a paywall, I'm liking GitAhead quite a lot.

But there's one thing that bugs me whenever I use it.

I'm talking about the remotes list in the side bar. Whenever I open or close a repo, for instance, all remotes get expanded. If I want to do something with a repo in these remotes, I have to collapse them all, find the one I'm interested in and expand it.

Then, next time I want to do something with another repo, I have to do that again because they all got expanded in the meanwhile.

I would prefer if GitAhead remembered which remotes are collapsed and which are expanded.

Thanks in advance.

**Comment by hackhaslam** [comment]
This is fixed in version 2.5.11.
