### ISSUE TITLE
Feature Request: Interrupt the attempt to fetch/pull/push from GitAhead, if the attempt to connect takes too long.

### ISSUE THREAD

**Issue by tommai78101** [gitahead/gitahead#304]
I'm on Ubuntu 18.04 LTS, using GitAhead 2.5.11 stable.

I'm able to use Git from the terminal to fetch/pull/push from a secured company Bitbucket repository, and I have valid git credentials to get Git to work. However, I'm not able to fetch/pull/push from GitAhead for some reasons, and have no idea where to find the issue.

When GitAhead is attempting to fetch/pull/push, the connection stays open for a long long time, and the UI is unresponsive despite it showing the loading circle animation. Hovering the mouse over the loading circle animation icon shows a cancel button, but once you click on that button, the entire UI stops responding to any user inputs. I can only exit out of GitAhead by pressing the Close button and wait for Ubuntu to force close the application, or by killing the process through the terminal.

I would like to request for a better thread interruption or a better method to stop the connection thread from doing a connection attempt, if the connection attempt is taking too long, or the user wants to cancel the connection. 

If possible, I would also want to see some additional logging/trace messages while attempting to connect to Bitbucket, and would hope to have a way to enable some debugging information, but I think that will be in its own separate issue.

Thanks

EDIT:

It may be possible that the git remote origin URL may be incorrect, and that I should be using some other URL string for Bitbucket, despite the URL being technically correct for Git terminal, and it being used when setting up the Bitbucket account in GitAhead. I'm unsure as to what Bitbucket Git repository URL format it should be, and whether or not the URL should contain additional information for GitAhead to process.

**Comment by kas-luthor** [comment]
libgit2 currently can't cancel initializing TCP connections. I'd suggest opening a feature request there

On a related note, there is an error in GitAhead which results in the running request not being canceled, which I've fixed in #324

**Comment by tommai78101** [comment]
Thanks, I'll take a look @kas-luthor

**Comment by hackhaslam** [comment]
I checked in a slightly different change to address the bug found by @kas-luthor. I will release a new build with that change soon.

**Comment by hackhaslam** [comment]
This should be fixed in 2.6.0.

**Comment by tommai78101** [comment]
Thanks!
