### ISSUE TITLE
macOS Update Installer fails if user is not admin

### ISSUE THREAD

**Issue by pbrunnen** [gitahead/gitahead#319]
Hello GitAhead team,
I run the macOS version of GitAhead and I have found that the update tool for the program does not handle the fact that I am not an admin user on my computer.

Thank you. -Peter.

**Comment by hackhaslam** [comment]
Unfortunately, this is a known issue. See #222.

**Comment by pbrunnen** [comment]
Hello @hackhaslam 
My apologies for not finding that... I thought I had searched, but apparently not correctly.
Thank you.
