### ISSUE TITLE
Contribute with translations

### ISSUE THREAD

**Issue by gustavovelascoh** [gitahead/gitahead#322]
Hi, I would like to contribute to Spanish translation but have no idea where to start; I couldn't find any translation files to start working on. Could you give me a hint on how to start?

**Comment by hackhaslam** [comment]
I need to set up the translation infrastructure and add an untranslated Spanish language translation file. I will let you know when that's ready.

**Comment by kas-luthor** [comment]
I'd like to provide a German translation as well

**Comment by hackhaslam** [comment]
@gustavovelascoh and @kas-luthor I just checked in basic support for using translation files. There are blank translation files for Spanish and German in the new `l10n` directory. You can manually edit those files or use the Qt Linguist tool. Then after you add a translation you can test it by simply rebuilding (e.g. just run `make` or `ninja`).

GitAhead builds its own translation files into the build directory and it also loads the Qt ones (for any language) from the Qt install directory. I still need to add the install rules for getting the translations into the packages.

Let me know if this works for you guys.

**Comment by gustavovelascoh** [comment]
@hackhaslam the translation configuration is working. However, as I'm using Ubuntu 18.04, I had to make some modifications in order to build and test the project successfully:

- Remove part of `pack/CMakeLists.txt` as described by @deadmozay in #219 
- Installed Qt 5.13.2 because the project needs "QRandomGenerator" which is available since version 5.10 (Also referred in #219, README.md should be updated )
- After the previous step,  QRandomGenerator header file was still not found so I added two lines to `CMakeLists.txt`:

```
...
if(UNIX AND NOT APPLE)
  set(CMAKE_EXE_LINKER_FLAGS -ldl)
  include_directories("${CMAKE_PREFIX_PATH}/include/QtCore") // +
  include_directories("${CMAKE_PREFIX_PATH}/include")             // +
endif()
...
```

- To execute the built project and test the translation I used:

```LANGUAGE=es_ES:es; ./GitAhead```

I am not sure if this was the right approach. I will let you know if I find any other issues.

**P.D.:** If someone else is willing to contribute to Spanish translation, we can split the load by "context" entities in the ```.ts``` file.

**Comment by hackhaslam** [comment]
@gustavovelascoh I don't think you should have to do this:

    ...
    if(UNIX AND NOT APPLE)
      set(CMAKE_EXE_LINKER_FLAGS -ldl)
      include_directories("${CMAKE_PREFIX_PATH}/include/QtCore") // +
      include_directories("${CMAKE_PREFIX_PATH}/include")             // +
    endif()
    ...

Did you restart from scratch with a new build directory after installing the new version of Qt?

**Comment by gustavovelascoh** [comment]
@hackhaslam You're right. It works without those new lines.

**Comment by hackhaslam** [comment]
@kas-luthor I'm going to make a new build soon. If you have any additional translation changes, let me know and I will hold off until you're ready.

**Comment by kas-luthor** [comment]
@hackhaslam I just opened #339

**Comment by kas-luthor** [comment]
@hackhaslam also, feel free to just rip the translation file from my fork's master, it usually contains all recent translations
