### ISSUE TITLE
Feature Request: Simplify pushing a tag

### ISSUE THREAD

**Issue by amatosg** [gitahead/gitahead#326]
I really love gitahead, but I think pushing a tag should be simpler than Remote >> Push to... etc. 
thanks!

**Comment by luriomer** [comment]
I agree, currently it's simpler to do it in the command line. Also, I add that it should be easier to edit/remove a remote tag. Currently, changing a local tag does not affect the remote one.

**Comment by hackhaslam** [comment]
@kas-luthor contributed several changes to address this issue.
