### ISSUE TITLE
Gitahead shows uncommitted changes in a clean repository

### ISSUE THREAD

**Issue by christiankral** [gitahead/gitahead#334]
I created the new local branch `patch-3qs` of someone else's fork `max-privato/patch-3`. I already pushed this branch to `origin` and yet there are uncommitted changes indicated. If I click on **Uncommitted changes** an empty **Diff view** is shown:

![image](https://user-images.githubusercontent.com/4184218/70447856-c6768600-1a9f-11ea-9375-9e38d4643ed4.png)

If I switch to the remote branch `origin/patch-3qs` then -- as expected -- no uncommitted changes are shown. 

![image](https://user-images.githubusercontent.com/4184218/70448352-882d9680-1aa0-11ea-85eb-127794ad15bd.png)

The git status of the [repository](https://github.com/christiankral/ModelicaStandardLibrary.git) shows:

```bash
ModelicaStandardLibrary> git status
On branch patch-3qs
Your branch is up to date with 'origin/patch-3qs'.

nothing to commit, working tree clean
```

**Comment by hackhaslam** [comment]
When you click on the gear button in the upper right corner of the history area, is the option to "Show Clean Status" enabled?

**Comment by christiankral** [comment]
Yes it does:

![image](https://user-images.githubusercontent.com/4184218/70459746-190e6d00-1ab5-11ea-84cc-4e21d6f93bea.png)

**Comment by hackhaslam** [comment]
Disable that to make the status go away when it's clean.

**Comment by christiankral** [comment]
OK, thanks for the hint; I thought it's a bug as it was not intuitive to me. Sorry for bothering you.

**Comment by hackhaslam** [comment]
That option is not checked by default, so it must have been turned on at some point. I don't think it's intuitive either, but it was requested by some users in the past.
