### ISSUE TITLE
How to change l10n?

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [gitahead/gitahead#349]
Since v2.6.0 I can use GitAhead only in German: how can I change the localization to English?

Vielen Dank!

**Comment by dgalli1** [comment]
If you're on Linux/Mac you can simple change how you start the program.
If you execute this in a terminal it should work:
`LANG=EN GitAhead`

I don't think theirs currently a possibility to do the same thing under windows.

**Comment by alessandrousseglioviretta** [comment]
`LANG=EN /Applications/GitAhead.app/Contents/MacOS/GitAhead` still shows the German locale (MacOS 10.14.6)

**Comment by hackhaslam** [comment]
There's a bug on macOS where it loads the German translation if it's in the list of preferred languages, even if it comes after English. See attached screenshot. The bug is already fixed, but I haven't been able to release a new build with the fix yet. The only workaround is to remove German from the the list of languages. I expect to release the fixed build within the next couple of days.

<img width="667" alt="Screen Shot 2019-12-24 at 8 07 25 PM" src="https://user-images.githubusercontent.com/6586470/71430482-56642480-2689-11ea-97fe-7130406ed165.png">

**Comment by hackhaslam** [comment]
This should be fixed now in build 2.6.1.

**Comment by Croydon** [comment]
I'm on Windows and have the same problem

My system language is German but I would like to continue to use gitahead in English. Is there currently a way to do this without changing my system settings?

If not, would it be reasonable to ask for such a gitahead language setting?

**Comment by hackhaslam** [comment]
@Croydon You have the same problem that English is first in the list of preferred languages, but GitAhead still loads the German translation?

**Comment by Croydon** [comment]
No, my system is in German and the preferred language is set to German in Windows. 
I don't want to change that, but I would like to use githead nonetheless in English.

Most applications allow to select manually the language which may differ from the system settings

**Comment by hackhaslam** [comment]
Do you have an example of a setting like that in other applications? I don't believe I've ever seen that.

**Comment by hackhaslam** [comment]
@Croydon I've added a command line flag to disable automatic loading of translation files for the next build. The flag is `--no-translation`.

**Comment by Masgalor** [comment]
I'm here for the same reason as @Croydon.
As he said, it's very common for software to have the option to set preferred locales.
Kind of strange you've never seen that before, maybe it's just a common thing in Germany.

However, here are some examples.

![waterfox](https://user-images.githubusercontent.com/30129213/73737194-7421b080-4742-11ea-8d0a-4958d126492d.png)
![plcdesigner](https://user-images.githubusercontent.com/30129213/73737195-7421b080-4742-11ea-834f-5a2600175402.png)

**Comment by andrbmgi** [comment]
Yes please. A build flag is not enough. I want my system in german but my team is international so naturally that stuff is in english. It would be nice if the automatically generated commit message would be created in english.

**Comment by Croydon** [comment]
Sorry, for my previous silence, too many notifications and things to do us usual....

I can only support this. It is pretty common for applications to offer such an option and people working in multiple languages would greatly benefit from this.

Thanks for the command line switch, but from a UX point of view this is not idealistic. 

Two more examples:


<details><summary>Thunderbird</summary>

![thunderbird](https://user-images.githubusercontent.com/1593194/77116909-44e4ab80-6a31-11ea-882c-ea5f5cfe4661.PNG)

</details>

<details><summary>LibreOffice</summary>

![libreoffice](https://user-images.githubusercontent.com/1593194/77116965-5d54c600-6a31-11ea-9760-a33390d91d9a.PNG)

</details>

**Comment by mgscreativa** [comment]
The same here, a GUI option to manually select default app language would be nice. Thanks a lot!

**Comment by disadamsdsdnts** [comment]
I want to +1 to the GUI option. Some terms in spanish are awful and not compatible with Git terminology. I have MacOS and English as primary language, but always starts in spanish.

**Comment by hackhaslam** [comment]
@disadamsdsdnts If you have English set as the first language in the list of preferred languages then it should start in English. That would be a bug. Are you using the very latest release?

**Comment by disadamsdsdnts** [comment]
@hackhaslam 

Downloaded yesterday from website. v2.6.2 (4 May 2020 - c8fffc0). I have MacOs High Sierra (10.13.6) and in Language & Region, I have English (U.S.) as primary. Basically the same as your screenshot.

With flag --no-translation I can see in english without a problem.

**Comment by carlosgdelvalle** [comment]
Temporary patch for Windows Users:
- Close GitAhead
- Delete ONLY the files of the -undesired- language from: [C:\Program Files\GitAhead\Resources\l10n](url)

**Comment by hackhaslam** [comment]
In the latest release (v2.6.3) there is an option in the GUI to disable translation:
<img width="493" alt="Screen Shot 2020-07-23 at 9 33 31 AM" src="https://user-images.githubusercontent.com/6586470/88306206-ae1e4900-ccc7-11ea-9ce4-2ebe27841075.png">

**Comment by carlosgdelvalle** [comment]
Updated! Thanks!
