### ISSUE TITLE
Failed to find SSH identity file when trying to pull

### ISSUE THREAD

**Issue by FinlayDaG33k** [gitahead/gitahead#350]
Hii there,

I've been trying to get GitAhead to use my SSH key.  
However, my SSH key is on my Yubikey and as such, doesn't exist as a file anywhere.  
I have gotten it to work with my regular `git` command just fine (I can pull and push just fine), however, when I try to use GitAhead, all I get is the error:
> Unable to fetch from 'origin' - failed to find SSH identity file

This indicates to me that GitAhead isn't using the same config as my CLI `git` command is this correct?  
Is there a way to either be able to use the SSH agent of CLI `git` that I've already set up on my machine with GitAhead?  
I know I *could* generate and add a new SSH key for this particular machine but I'd like to just be able to use the SSH key that is on my Yubi :) 

I'm currently using version `2.6.0` (yes, I know there is an update available) on Manjaro.

**Comment by hackhaslam** [comment]
GitAhead tries to read config values from your OpenSSH config file (~/.ssh/config), but it does not delegate to OpenSSH like git does. Instead, it uses libssh2 (via libgit2). I don't know if there is any support for Yubikey in libssh2 (or libgit2). How do you configure SSH to use Yubikey?

**Comment by FinlayDaG33k** [comment]
Thanks for your quick reply.
Happy new year already btw if you don't have time to reply :)

I have setup SSH using the GnuPG's ssh support.
I don't know if you're familiar with using GPG for SSH authentication?
In case you aren't, here is a little bit of information (disclaimer, I'm not affiliated with any brands I name below):

Typically (read: in the most common setup) your GPG key (this can be stored on your local machine or on something like a HSM - like the Yubikey and NitroKey - or a more "simplistic" smartcard - like the OpenPGP Smartcard) consists of 3 certificates (though, they can be jammed into one big certificate if you want to... for w/e reason):
- a signing certificate
- an encryption certificate
- an authentication certificate

That authentication certificate can also be used for SSH.  
As such, I have setup my local `gpg` client (built-in into *most* gnu+Linux distros) to be used as the authentication "thing" (by lack of other words) for OpenSSH.
But as you said, GitAhead used libgit2 instead of my local git client (which I thought it did since `git` is listed as a dependency for GitAhead), which also explains another (smaller) issue where GitAhead wouldn't sign my commits using my yubikey either (whereas the CLI `git` would do so).

I'll have a look towards libssh2 and libgit2 to see whether I can find a solution for it.  
I wonder if anybody else ran into this issue (but never reported it here).

**Comment by hackhaslam** [comment]
GitAhead already supports reading keys from the ssh agent if it can find one running. It looks for the SSH_AUTH_SOCK environment variable. Do you have that environment variable set?

**Comment by FinlayDaG33k** [comment]
Yes, this is set to `/run/user/1000/gnupg/S.gpg-agent.ssh`

**Comment by FinlayDaG33k** [comment]
I've added it to my `~/.xprofile` and now GitAhead also picks up on it :)

**Comment by ThomDietrich** [comment]
Was this ever documented anywhere? How would one set this on a macos system?

```
echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.hktd4zJkti/Listeners
```
