### ISSUE TITLE
Feature request: Windows version need Unicode support.

### ISSUE THREAD

**Issue by dk1507** [gitahead/gitahead#351]
The application is perfect to me comparing to other git GUI variations. The only shortcut is encoding selection not avilable. Shall we added unicode support or better still encoding option?

Thanks,
David

**Comment by hackhaslam** [comment]
GitAhead supports unicode and there is an option choose the character encoding of diffs at Tools -> Options... -> Diff -> Character Encoding. If you have a different concern, then please clarify.
