### ISSUE TITLE
Changes of file with long lines are not displayed correctly 

### ISSUE THREAD

**Issue by christiankral** [gitahead/gitahead#352]
Consider the change of a text file with short line lengths: Everything looks OK:

![image](https://user-images.githubusercontent.com/4184218/71815620-5815eb00-3080-11ea-81d6-c0c717d7ba17.png)

If the changes instead are made with long line lengths which exceed the window length of gitahead, the changes are not fully displayed, as the last line (line 11) is only partly shown:

![image](https://user-images.githubusercontent.com/4184218/71815684-8eec0100-3080-11ea-8bcc-b43c3b829691.png)

This issue applies to v2.6.1

**Comment by hackhaslam** [comment]
This is issue #60.
