### ISSUE TITLE
[Feature request] Partial commits

### ISSUE THREAD

**Issue by KaKi87** [gitahead/gitahead#366]
Hello,

I'd like to be able to make partial commits (i.e. committing specific lines of specific files) [just like in GitHub Desktop](https://github.blog/2015-01-14-partial-commits-in-github-for-windows/).

Thanks

**Comment by tommai78101** [comment]
In other words, you want interactive staging using `git add -i` or `git add -p`.

**Comment by dcendents** [comment]
This looks like a duplicate of #344

**Comment by hackhaslam** [comment]
Agreed.

**Comment by KaKi87** [comment]
Yes indeed, I didn't found out how to check. Thanks !
