### ISSUE TITLE
Feature Request: “Open existing repository” into a “Remote” list?

### ISSUE THREAD

**Issue by maresb** [gitahead/gitahead#368]
Also [posted at StackOverflow](https://stackoverflow.com/q/60006364/10155767) with no response.

I cloned a repository from GitLab with the command line. I added it to the left-hand pane of GitAhead by clicking ```+``` and ```Open Existing Repository```.  As expected, it appears in the "Open" and "Recent" lists.  

The repository is also listed in "Remote" under my GitLab account, but with a "download from cloud" icon.  Thus it does not recognize that the repository which I already added corresponds with the remote repository, despite that my existing clone has the same name and the appropriate SSH remote origin.  **How do I make GitAhead recognize that my existing repository is a clone from my GitLab account, so that it opens when I double-click the corresponding entry under "Remote"?**

My attempts are:

1. Double-clicking on the remote repository entry leads to a "Clone Repository" dialog.  I tried pointing this to the existing clone, but it failed because the directory was nonempty.

2. I edited `GitAhead.conf` and added a line under `[remote]` of the form `gitlab\username\repo-name=/path/to/clone`. This is fine for one time, but I'd like to learn how to do it from the GUI if possible.

Am I missing something, or is this not yet a feature?

**Comment by hackhaslam** [comment]
This used to be a feature, but it doesn't look like it's possible any longer. I'll look at adding it soon.

BTW, I thought that I was getting notifications for new questions on SO, but I'm not. I need to figure out why that's not working for me.
