### ISSUE TITLE
Fetch All causes Gitahead to crash when no repository is opened

### ISSUE THREAD

**Issue by christiankral** [gitahead/gitahead#382]
If Gitahead is started without opening a repository the file menu `Fetch All` is not disabled. When clicking on this entry Gitahead crashes.  

![image](https://user-images.githubusercontent.com/4184218/75570755-17bb6380-5a58-11ea-8be4-e8db88101d56.png)

I think the Menu entry `Fetch All` shall not be accessible (grayed out) if no repository is opened.

**Comment by Maickonn** [comment]
Thanks for reporting this.
I will fix this.

**Comment by hackhaslam** [comment]
Should now be fixed in 2.6.2.
