### ISSUE TITLE
errors in bookmark window

### ISSUE THREAD

**Issue by gh16683170** [gitahead/gitahead#387]
Open preview window, toggle sync in the preview window, add some bookmark from the editor window and preview window, in different files. Then the bookmark shows errors.

It is a 100% reproduced bug, in build 1017(the latest and previous version).

![image](https://user-images.githubusercontent.com/16650849/75839612-2f05a280-5e04-11ea-8639-18eaa029528c.png)
![image](https://user-images.githubusercontent.com/16650849/75839621-375ddd80-5e04-11ea-939f-0a1e564c3fab.png)

**Comment by hackhaslam** [comment]
This issue tracker is not for understand. The support team has received your email and will respond appropriately.
