### ISSUE TITLE
Apply window size/position on command line launch

### ISSUE THREAD

**Issue by CrendKing** [gitahead/gitahead#389]
Normally when I launch the application, the last used window size and position are remembered and restored. However if I specify a repository as command argument, the application is launch with default size and center position. This seems inconsistent and could be a bug, either in GitAhead or Qt.

### Steps to reproduce
Open a terminal. Run "<GitAhead.exe> <repository_path>". For example, `C:\GitAhead\GitAhead.exe D:\Repos\Test`.

### Expected result
The window has last used size (e.g. maximized).

### Actual result
The window is normal sized.

### Other
When not specifying the repository argument, it works as expected.

### Environment
GitAhead 2.6.1. Windows 10 64-bit Build 1909.

**Comment by hackhaslam** [comment]
It's not a bug per se. Specifying a repository on the command line isn't supposed to restore open repositories or any of the settings. However, I can see how you would want window size and position to be remembered even when not restoring open repositories. I will likely change this.

**Comment by CrendKing** [comment]
Or an argument to control the behavior. Or an option. Anything. Thanks!
