### ISSUE TITLE
Unable to fetch from 'origin' - unexpected HTTP status code: 404

### ISSUE THREAD

**Issue by hacheraw** [gitahead/gitahead#395]
I switched from GitKraken to GitAhead in linux.
My already configured and working repository has a gitlab origin.

I opened the repository in GitAhead and whenever I try to fetch, pull or push I got this error:

```
Unable to {whatever I'm doing} from 'origin' - unexpected HTTP status code: 404
```
If I use the linux terminal, I can fetch, pull and push normally.

I don't know if the problem is GitAhead not asking for credentials.

- I've configured my username and email on general and repository config.
- I've tried to add and remove a gitlab account (using personal access token)

Any ideas?

```
# cat ./.git/config

[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://gitlab.com/c****c/a****3.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
	remote = origin
	merge = refs/heads/develop
[branch "master"]
	remote = origin
	merge = refs/heads/master
[user]
	name = Jorge
	email = j****z@c****c.com
```

**Comment by hackhaslam** [comment]
The username and email in git config is for signing commits. A GitLab personal access token would be for connecting to the GitLab API. Neither is used for authenticating with HTTPS hosts.

It may be that you have credentials stored in your credential manager (e.g. gnome-keyring) that are stale, but GitAhead is still picking up. Try temporarily adding username and password directly to the remote URL:

    https://username:password@gitlab.com/...

You could also try with just the username to see if it prompts for the password.

**Comment by hacheraw** [comment]
Deleting stored credential in Linux "Password and keys" did the trick. Upon startting GitAhead, it asked for credentials.

Thank you.
