### ISSUE TITLE
About large file size warning

### ISSUE THREAD

**Issue by Maickonn** [gitahead/gitahead#400]
Hi, @hackhaslam !

I was thinking, when checking the option "**Stop prompting to stage large files**", should I save in the configuration that the user would not like to receive this question again even after reopening the software? Because it is not currently being saved in the settings file.

If so, I would like to make this change.

![Untitled](https://user-images.githubusercontent.com/1365683/78735607-904bf480-7921-11ea-8201-02980035fa1b.png)

**Comment by hackhaslam** [comment]
Yes, I think that would be reasonable. If you decide to add this, there are already a bunch of similar "prompt" settings. They have their own section in the Window preferences panel. It would be nice if this behaved in a similar way.

**Comment by Maickonn** [comment]
Right, I will implement it. 
Thanks.
