### ISSUE TITLE
crash on macOS when closing app

### ISSUE THREAD

**Issue by minusf** [gitahead/gitahead#407]
please find at a stack strace here: https://gist.github.com/minusf/b77f5b23d5d3d809511c40fdfc5e39aa

This has happened with latest gitahead when closing the last window.

**Comment by hackhaslam** [comment]
This was fixed by 56b1f47375db72f2be6ccaafd73e9acc7d0aec27. It will be in the next build.

**Comment by hackhaslam** [comment]
Should now be fixed in 2.6.2.
