### ISSUE TITLE
Brazilian Portuguese translation

### ISSUE THREAD

**Issue by gomes2191** [gitahead/gitahead#411]
It would be possible for a Brazilian Portuguese translation to be available to carry out the translation.

**Comment by hackhaslam** [comment]
Eu até falo português (pq minha esposa é brasileira e passei alguns anos morando no Brasil), mas não me arrisco a fazer a tradução. Meu primeiro idioma é ingles. Se vc quiser tentar fazer a tradução eu posso adicionar os arquivos.

**Comment by hackhaslam** [comment]
I just added a file at `l10n/gitahead_pt_BR.ts`. You can update it with Qt Linguist or just manually add the translations to the XML file. After you've added the translations submit a pull request.

**Comment by gomes2191** [comment]
Beauty I will continue the translation process

**Comment by gomes2191** [comment]
@hackhaslam I will continue to translate and correct errors in the translation, in the future I will upload a translation update.
