### ISSUE TITLE
Allow '-' char in advanced search to find JIRA Issues

### ISSUE THREAD

**Issue by talesmetal** [gitahead/gitahead#423]
I would like to search in git comments strings like this JIRA-25454 and there is no possible, and I don't know if it's possible to accept '-' char, I've found this in GenericLexer.cpp

case Identifier: {
        char nextCh = safeAt(mBuffer, mIndex + 1);
        bool compound = **(ch == '-' || ch == '\'')** && isAlpha(nextCh);
        if (ch != '_' && !alpha && !digit && !compound)
          return {Identifier, mBuffer.mid(startPos, mIndex - startPos)};
        break;
      }

I tried to change it and compile it under Linux but I had problems when I tried to compile

**Comment by hackhaslam** [comment]
Oh right. It should allow either an alphabetic or numeric character after the dash. I can can change it.

**Comment by talesmetal** [comment]
How long it takes to add this feature?

**Comment by hackhaslam** [comment]
The fix is quick, but I just released a new build. I'm not sure when I'll make another one.

**Comment by hackhaslam** [comment]
This is fixed by bbb4f78a735fac5264ff895ba8499a064cb65155.

**Comment by hackhaslam** [comment]
Fix included in 2.6.3.

**Comment by thebiguno** [comment]
I am not sure that this is working... I have exactly the same use case as talesmetal - searching for Jira tickets in commit messages.  I tried using the basic search, the advanced search (in the Comment section), and can't seem to get it to consistently search within commit messages.  Whenever I search a Jira ticket number, nothing is returned.  However even alpha searching seems to be a bit strange - for instance, if I search for "fixe" it won't match tickets with the word "fixed" in the comments.  Personally, I would expect the search field (or if nothing else, the comment search field) to just do a contains search within all comments.

**Comment by hackhaslam** [comment]
The search is an indexed search. Searching for "fixe" is not expected to return any results. You should see auto-complete suggestions that you can choose from. Search for "fixe*" to find terms that start with "fixe".

If you had already opened this repository with a previous version, you'll have to remove the old index to cause it to index again. Open the search panel in repository config:

<img width="506" alt="Screen Shot 2020-07-15 at 4 02 03 PM" src="https://user-images.githubusercontent.com/6586470/87602779-d6e58380-c6b4-11ea-9810-ef3840ec835b.png">

Click the "Remove" button then uncheck and recheck the "Enable" check box to start indexing. I could have bumped the index version for this change to get everything to start indexing again, but I didn't.

**Comment by thebiguno** [comment]
Ahh, removing and re-creating the index seems to do it.  Thanks for the help!
