### ISSUE TITLE
BUG: Moved files to another directory

### ISSUE THREAD

**Issue by Maickonn** [gitahead/gitahead#428]
Hello, @hackhaslam 

I'm having trouble fixing this problem. When you move a file to another directory and mark the directory on the stage, when committing, the identification to remove the file from the previous directory is not working. Then you need to commit again.

I haven't found in the code where I can be correcting this. Could you guide me?

![Untitled Project](https://user-images.githubusercontent.com/1365683/81724291-822a5000-945a-11ea-8127-88d71ef3430f.gif)

**Comment by Maickonn** [comment]
I was able to find where the problem occurs. It is located at "**void Diff::findSimilar()**". For some reason, it is being called while the files are still in stage mode. I will continue to investigate this.

**Comment by Maickonn** [comment]
I commented the line 297 of Repository.cpp and that solved the problem. Can you tell me why the method is being called there?

![Annotation 2020-05-13 192011](https://user-images.githubusercontent.com/1365683/81871945-2beb0900-954f-11ea-997f-b5b635cf2022.jpg)

**Comment by hackhaslam** [comment]
`Diff::findSimilar` is what is supposed to detect when files are renamed (or moved) instead of deleted and added. Apparently that doesn't work when the file is moved into an untracked directory. It does detect the rename after you stage the directory, but by then it's too late to correctly stage the deletion of the old file.

Removing the call to `Diff::findSimilar` is not an appropriate fix. Staging an untracked folder should probably trigger some special logic to look for renames and then manually stage the deletion of the old file.

**Comment by Maickonn** [comment]
> `Diff::findSimilar` is what is supposed to detect when files are renamed (or moved) instead of deleted and added. Apparently that doesn't work when the file is moved into an untracked directory. It does detect the rename after you stage the directory, but by then it's too late to correctly stage the deletion of the old file.
> 
> Removing the call to `Diff::findSimilar` is not an appropriate fix. Staging an untracked folder should probably trigger some special logic to look for renames and then manually stage the deletion of the old file.

Yes, the purpose of the method I understood. But I believe there is no need to leave it at "**Diff Repository::status**". The problem (similar to what you mentioned) is that when **setDiff** occurs to populate the list of files, if you check the checkbox of a folder containing the moved file, this calls "**Diff::findSimilar**" in the "**Diff Repository::status**", preventing the list from being populated with the file from the previous directory. Causing the bug in manual stages.

I performed several tests, with several directories, files and had no more problems.

**Comment by Maickonn** [comment]
After the commit, all changes continue with the similarity normally.

**Comment by Maickonn** [comment]
@hackhaslam I will make the pull request so that we can work on the possible solution.

**Comment by hackhaslam** [comment]
It's supposed to allow the status diff to show renames. Whether that's working or not (it sounds like you're saying it's not?) I don't know.
