### ISSUE TITLE
How about move from QWidget to QML in separate branch?

### ISSUE THREAD

**Issue by ArtifeksNN** [gitahead/gitahead#448]
I really like to use the current version, but it would be nice to bring the new ui \ ux to gitAhead and make it the coolest and without limits. I have expertise in moving desktop applications from widgets to qml and in using qml for 4th years. It would be cool if we in a separate branch started a little bit of moving the whole community. What do you think about it?

**Comment by hackhaslam** [comment]
I don't have much interest in moving to QML. I think this would have to happen in a fork.
