### ISSUE TITLE
Update to 2.6.3 from 2.6.2 fails

### ISSUE THREAD

**Issue by TheBlipBloop** [gitahead/gitahead#461]
Hello!

Updating to 2.6.3 fails with error code 1

![image](https://user-images.githubusercontent.com/42724393/87484074-2f038380-c5ea-11ea-9ea0-c138da75e668.png)

GitAhead: 2.6.2
OS: Ubuntu 20.04

**Comment by hackhaslam** [comment]
Is it possible the current user doesn't have permissions to remove the existing version? Try running the install script manually.

**Comment by TheBlipBloop** [comment]
Whoops, I wasn't running it with proper permission. It works now thanks!
