### ISSUE TITLE
Horizontal Scrollbar hides last line (from v2.6.3)

### ISSUE THREAD

**Issue by dedece35** [gitahead/gitahead#470]
Hello,

i just upgrade my gitAhead application to last version (2.6.3).
When I view one commit and have a a horizontal scrollbar, the last line is hidden by this scrollbar.
To see my last line, I have to select all the content of one file with my mouse and without releasing it, then go down.

It's a quite annoying.

Could you please correct this pb to come back to the previous user experience ?

regards,
David.

**Comment by hackhaslam** [comment]
This isn't a new problem. See #60. I will test the fix by @stefanknotzer.

**Comment by dedece35** [comment]
hello @hackhaslam .
OK, sorry, I didn't see it ...
For me, it seems to be appeared in the last version. Sorry again.
I close this issue
