### ISSUE TITLE
"View getting started videos" Link Does Not Have Any Videos

### ISSUE THREAD

**Issue by LisaCee** [gitahead/gitahead#476]
On the start screen there is a link to "View getting started videos."  While the name of the page it links to makes sense, [#tutorials](https://gitahead.github.io/gitahead.com/#tutorials), there are no videos on the page.  

I would suggest either linking directly to your [YouTube playlist ](https://www.youtube.com/playlist?list=PLkhgTa3ULplz_DgalwtORMviEJeHy07EB) or at least adding a link to it from the #tutorials page.

**Comment by hackhaslam** [comment]
I fixed this with a redirect on the site.
