### ISSUE TITLE
Is the project still alive or not maintained anymore?

### ISSUE THREAD

**Issue by ppkozlowski** [gitahead/gitahead#606]
Hi guys!

Thanks for great piece of software! I would like to know if GitAhead is active and maintain or is dead project? I don't see new pull requests accepted to master branch. The latest was commit 7 months ago.

@hackhaslam Let us know if we can help you the provide better stability and continuity of project.

Thanks
Piotr

**Comment by gomes2191** [comment]
As far as I know, the maintainer is very busy and at the moment he is not able to continue the project.

**Comment by Philipp91** [comment]
I'd be happy to review some of the pull requests and help setting up a way of deploying this to some linux package repository that allows for automatic updates.

**Comment by gomes2191** [comment]
@Jason Haslam

**Comment by gomes2191** [comment]
@hackhaslam

**Comment by hackhaslam** [comment]
See issue #598. That has some of my current thoughts. I still need to update the README to reflect the current status of the project.
