### ISSUE TITLE
Login error (Windows 10) & Crashing

### ISSUE THREAD

**Issue by zhaolinlau** [gitahead/gitahead#613]
Can't log in to GitHub and GitLab(I'm not sure about the other platforms) with password, and I didn't enable two-factor authentication. The only way to login is using an access token. And yea, will sometimes crash.

**Comment by crzyhorse** [comment]
As of August 13, 2021 GitHub requires token authentication for all authenticated actions. https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by zhaolinlau** [comment]
> 
> 
> As of August 13, 2021 GitHub requires token authentication for all authenticated actions. https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

ok i got it
