### ISSUE TITLE
New created repositories from Github and Gitlab account won't be updated in real time(Windows 10)

### ISSUE THREAD

**Issue by zhaolinlau** [gitahead/gitahead#614]
So, the problem is if I don't reopen the GitAhead then the new repositories which just created on Github or Gitlab won't be updated onto GitAhead's Github & Gitlab account in real time.

**Comment by hackhaslam** [comment]
This is a known limitation. Click on the gear icon in the bottom of the sidebar and choose "Refresh Remote Accounts".

**Comment by zhaolinlau** [comment]
> 
> 
> This is a known limitation. Click on the gear icon in the bottom of the sidebar and choose "Refresh Remote Accounts".

oh I got it. Well, I suggest to put the "Refresh Remote Accounts" in right click option to be more obvious and easier to find out.
