### ISSUE TITLE
Nice work! Also has an active community growing...

### ISSUE THREAD

**Issue by nickl-** [gitahead/gitahead#628]
Just wanted to pop in and say kudos for all the hard work. Feel free to close this issue.

I installed the client and was able to nit pick my changes for separate commits and push it off to an additional remote which I could pleasantly set as default upstream all while performing the push, nice. Created a new branch with additional commits all without a snag.

Sure there is still a lot of work to be done, but obviously there is also a lot of interest and willingness to help. From my experience don't wait for people to offer to help, if their work looks like they know what they are doing, just add them to the project and tell them to merge their own PRs. =)

Ride this wave of interest by utilizing the available resources and getting more people on board. No need to hack at it all alone. The first step is the license the next step is open the repos and watch it soar. 

Hey what's the worst that can happen? This is source controlled you might need to roll back a few commits if you're concerned. But don't be, there are resources here that are much better than hiring an intern or graduate and they are eager to work now. Everybody has their own lives so interest quickly fades. Just make the most of it is all I'm trying to say.

Thanks for the good work! You're a superstar!!

**Comment by wpostma** [comment]
Hey, I wouldn't mind contributing some changes to this code. Are you doing a fork?

1.   The GUI has a LOT Of rough edges and crashes a lot.
2.   The push feature shouldn't assume randomly one remote but rather ask for each push.
3.   The gitconfig property for default repo to push to is a well known value and should be respected.
4.   There's no log history search and no proper code search, only a single commit diff search.

**Comment by nickl-** [comment]
@wpostma No fork, I suggest try ping the project team
