### ISSUE TITLE
Update via Pamac fails to build

### ISSUE THREAD

**Issue by php4fan** [gitahead/gitahead#647]
Some time ago I installed Gitahead on my Manjaro system via Pamac.
I never used it, maybe I tried it and then I forgot about it.

Today I installed a bunch of updates with Pamac, one of them was Gitahead.

First I got this error in Pamac immediately after selecting the available updates including Gitahead and clicking Apply:

![image](https://github.com/gitahead/gitahead/assets/13969584/93b767aa-5ada-4a46-9052-5cd54b86203a)

Then I tried again and this time, it proceeded to the next step, took ridiculously long to build gitahead, and at the end I got this error:

(see attached txt file)

[gitahead_pamac_error.txt](https://github.com/gitahead/gitahead/files/13746688/gitahead_pamac_error.txt)

**Comment by hackhaslam** [comment]
An update *was* recently released, but I don't know anything about Pamac. You'll have to talk to the packager if you're interested in using it.
